title: Elysian Roleplay
description: A well-made gamemode for open.mp server.
remote_theme: pages-themes/hacker@v0.2.0
show_downloads: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
